// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: block.proto

package one.contentbox.boxd.proto;

public interface BlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corepb.Block)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.corepb.BlockHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.corepb.BlockHeader header = 1;</code>
   */
  one.contentbox.boxd.proto.BlockHeader getHeader();
  /**
   * <code>.corepb.BlockHeader header = 1;</code>
   */
  one.contentbox.boxd.proto.BlockHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .corepb.Transaction txs = 2;</code>
   */
  java.util.List<one.contentbox.boxd.proto.Transaction> 
      getTxsList();
  /**
   * <code>repeated .corepb.Transaction txs = 2;</code>
   */
  one.contentbox.boxd.proto.Transaction getTxs(int index);
  /**
   * <code>repeated .corepb.Transaction txs = 2;</code>
   */
  int getTxsCount();
  /**
   * <code>repeated .corepb.Transaction txs = 2;</code>
   */
  java.util.List<? extends one.contentbox.boxd.proto.TransactionOrBuilder> 
      getTxsOrBuilderList();
  /**
   * <code>repeated .corepb.Transaction txs = 2;</code>
   */
  one.contentbox.boxd.proto.TransactionOrBuilder getTxsOrBuilder(
      int index);

  /**
   * <code>uint32 height = 3;</code>
   */
  int getHeight();

  /**
   * <code>bytes signature = 4;</code>
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <code>.corepb.IrreversibleInfo irreversible_info = 5;</code>
   */
  boolean hasIrreversibleInfo();
  /**
   * <code>.corepb.IrreversibleInfo irreversible_info = 5;</code>
   */
  one.contentbox.boxd.proto.IrreversibleInfo getIrreversibleInfo();
  /**
   * <code>.corepb.IrreversibleInfo irreversible_info = 5;</code>
   */
  one.contentbox.boxd.proto.IrreversibleInfoOrBuilder getIrreversibleInfoOrBuilder();
}
