// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: faucet.proto

package one.contentbox.boxd.proto;

public interface ClaimReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.ClaimReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string addr = 1;</code>
   */
  java.lang.String getAddr();
  /**
   * <code>string addr = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddrBytes();

  /**
   * <code>uint64 amount = 2;</code>
   */
  long getAmount();
}
