// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: faucet.proto

package one.contentbox.boxd.proto;

public interface ClaimRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.ClaimResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string hash = 3;</code>
   */
  java.lang.String getHash();
  /**
   * <code>string hash = 3;</code>
   */
  com.google.protobuf.ByteString
      getHashBytes();
}
