// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db.proto

package one.contentbox.boxd.proto;

public final class DbProto {
  private DbProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_GetDatabaseKeysRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_GetDatabaseKeysRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_GetDatabaseKeysResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_GetDatabaseKeysResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_GetDatabaseValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_GetDatabaseValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_GetDatabaseValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_GetDatabaseValueResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010db.proto\022\005rpcpb\"T\n\026GetDatabaseKeysRequ" +
      "est\022\r\n\005table\030\001 \001(\t\022\016\n\006prefix\030\002 \001(\t\022\014\n\004sk" +
      "ip\030\003 \001(\005\022\r\n\005limit\030\004 \001(\005\"T\n\027GetDatabaseKe" +
      "ysResponse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(" +
      "\t\022\014\n\004skip\030\003 \001(\005\022\014\n\004keys\030\004 \003(\t\"5\n\027GetData" +
      "baseValueRequest\022\r\n\005table\030\001 \001(\t\022\013\n\003key\030\002" +
      " \001(\t\"H\n\030GetDatabaseValueResponse\022\014\n\004code" +
      "\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\r\n\005value\030\003 \001(\0142\270" +
      "\001\n\017DatabaseCommand\022P\n\017GetDatabaseKeys\022\035." +
      "rpcpb.GetDatabaseKeysRequest\032\036.rpcpb.Get",
      "DatabaseKeysResponse\022S\n\020GetDatabaseValue" +
      "\022\036.rpcpb.GetDatabaseValueRequest\032\037.rpcpb" +
      ".GetDatabaseValueResponseB&\n\031one.content" +
      "box.boxd.protoB\007DbProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rpcpb_GetDatabaseKeysRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpcpb_GetDatabaseKeysRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_GetDatabaseKeysRequest_descriptor,
        new java.lang.String[] { "Table", "Prefix", "Skip", "Limit", });
    internal_static_rpcpb_GetDatabaseKeysResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpcpb_GetDatabaseKeysResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_GetDatabaseKeysResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Skip", "Keys", });
    internal_static_rpcpb_GetDatabaseValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpcpb_GetDatabaseValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_GetDatabaseValueRequest_descriptor,
        new java.lang.String[] { "Table", "Key", });
    internal_static_rpcpb_GetDatabaseValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpcpb_GetDatabaseValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_GetDatabaseValueResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
