// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package one.contentbox.boxd.proto;

public interface FetchUtxosRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.FetchUtxosResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .rpcpb.Utxo utxos = 3;</code>
   */
  java.util.List<one.contentbox.boxd.proto.Utxo> 
      getUtxosList();
  /**
   * <code>repeated .rpcpb.Utxo utxos = 3;</code>
   */
  one.contentbox.boxd.proto.Utxo getUtxos(int index);
  /**
   * <code>repeated .rpcpb.Utxo utxos = 3;</code>
   */
  int getUtxosCount();
  /**
   * <code>repeated .rpcpb.Utxo utxos = 3;</code>
   */
  java.util.List<? extends one.contentbox.boxd.proto.UtxoOrBuilder> 
      getUtxosOrBuilderList();
  /**
   * <code>repeated .rpcpb.Utxo utxos = 3;</code>
   */
  one.contentbox.boxd.proto.UtxoOrBuilder getUtxosOrBuilder(
      int index);
}
