// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db.proto

package one.contentbox.boxd.proto;

public interface GetDatabaseKeysResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.GetDatabaseKeysResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 skip = 3;</code>
   */
  int getSkip();

  /**
   * <code>repeated string keys = 4;</code>
   */
  java.util.List<java.lang.String>
      getKeysList();
  /**
   * <code>repeated string keys = 4;</code>
   */
  int getKeysCount();
  /**
   * <code>repeated string keys = 4;</code>
   */
  java.lang.String getKeys(int index);
  /**
   * <code>repeated string keys = 4;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);
}
