// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package one.contentbox.boxd.proto;

public interface MakeTokenIssueTxReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcpb.MakeTokenIssueTxReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string issuer = 1;</code>
   */
  java.lang.String getIssuer();
  /**
   * <code>string issuer = 1;</code>
   */
  com.google.protobuf.ByteString
      getIssuerBytes();

  /**
   * <code>string issuee = 2;</code>
   */
  java.lang.String getIssuee();
  /**
   * <code>string issuee = 2;</code>
   */
  com.google.protobuf.ByteString
      getIssueeBytes();

  /**
   * <code>.rpcpb.TokenTag tag = 3;</code>
   */
  boolean hasTag();
  /**
   * <code>.rpcpb.TokenTag tag = 3;</code>
   */
  one.contentbox.boxd.proto.TokenTag getTag();
  /**
   * <code>.rpcpb.TokenTag tag = 3;</code>
   */
  one.contentbox.boxd.proto.TokenTagOrBuilder getTagOrBuilder();

  /**
   * <code>uint64 fee = 4;</code>
   */
  long getFee();
}
