// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: block.proto

package one.contentbox.boxd.proto;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corepb.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   */
  int getVersion();

  /**
   * <code>repeated .corepb.TxIn vin = 2;</code>
   */
  java.util.List<one.contentbox.boxd.proto.TxIn> 
      getVinList();
  /**
   * <code>repeated .corepb.TxIn vin = 2;</code>
   */
  one.contentbox.boxd.proto.TxIn getVin(int index);
  /**
   * <code>repeated .corepb.TxIn vin = 2;</code>
   */
  int getVinCount();
  /**
   * <code>repeated .corepb.TxIn vin = 2;</code>
   */
  java.util.List<? extends one.contentbox.boxd.proto.TxInOrBuilder> 
      getVinOrBuilderList();
  /**
   * <code>repeated .corepb.TxIn vin = 2;</code>
   */
  one.contentbox.boxd.proto.TxInOrBuilder getVinOrBuilder(
      int index);

  /**
   * <code>repeated .corepb.TxOut vout = 3;</code>
   */
  java.util.List<one.contentbox.boxd.proto.TxOut> 
      getVoutList();
  /**
   * <code>repeated .corepb.TxOut vout = 3;</code>
   */
  one.contentbox.boxd.proto.TxOut getVout(int index);
  /**
   * <code>repeated .corepb.TxOut vout = 3;</code>
   */
  int getVoutCount();
  /**
   * <code>repeated .corepb.TxOut vout = 3;</code>
   */
  java.util.List<? extends one.contentbox.boxd.proto.TxOutOrBuilder> 
      getVoutOrBuilderList();
  /**
   * <code>repeated .corepb.TxOut vout = 3;</code>
   */
  one.contentbox.boxd.proto.TxOutOrBuilder getVoutOrBuilder(
      int index);

  /**
   * <code>.corepb.Data data = 4;</code>
   */
  boolean hasData();
  /**
   * <code>.corepb.Data data = 4;</code>
   */
  one.contentbox.boxd.proto.Data getData();
  /**
   * <code>.corepb.Data data = 4;</code>
   */
  one.contentbox.boxd.proto.DataOrBuilder getDataOrBuilder();

  /**
   * <code>uint32 magic = 5;</code>
   */
  int getMagic();

  /**
   * <code>int64 lock_time = 6;</code>
   */
  long getLockTime();
}
