// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web.proto

package one.contentbox.boxd.proto;

public final class WebProto {
  private WebProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ViewTxDetailReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ViewTxDetailReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ViewTxDetailResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ViewTxDetailResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ViewBlockDetailReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ViewBlockDetailReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ViewBlockDetailResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ViewBlockDetailResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_ListenBlocksReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_ListenBlocksReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_TxDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_TxDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_TxInDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_TxInDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_TxOutDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_TxOutDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_BlockDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_BlockDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_TokenIssueInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_TokenIssueInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_SplitContractInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_SplitContractInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcpb_TokenTransferInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcpb_TokenTransferInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tweb.proto\022\005rpcpb\032\021transaction.proto\"5\n" +
      "\017ViewTxDetailReq\022\014\n\004hash\030\001 \001(\t\022\024\n\014spread" +
      "_split\030\002 \001(\010\"\201\002\n\020ViewTxDetailResp\022\014\n\004cod" +
      "e\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\017\n\007version\030\003 \001(" +
      "\005\022\022\n\nblock_time\030\004 \001(\003\022\024\n\014block_height\030\005 " +
      "\001(\r\0220\n\006status\030\006 \001(\0162 .rpcpb.ViewTxDetail" +
      "Resp.TxStatus\022\037\n\006detail\030\007 \001(\0132\017.rpcpb.Tx" +
      "Detail\"@\n\010TxStatus\022\013\n\007unknown\020\000\022\013\n\007pendi" +
      "ng\020\001\022\013\n\007onchain\020\002\022\r\n\tconfirmed\020\003\"\"\n\022View" +
      "BlockDetailReq\022\014\n\004hash\030\001 \001(\t\"X\n\023ViewBloc",
      "kDetailResp\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001" +
      "(\t\022\"\n\006detail\030\003 \001(\0132\022.rpcpb.BlockDetail\"\021" +
      "\n\017ListenBlocksReq\"Z\n\010TxDetail\022\014\n\004hash\030\001 " +
      "\001(\t\022\036\n\003vin\030\002 \003(\0132\021.rpcpb.TxInDetail\022 \n\004v" +
      "out\030\003 \003(\0132\022.rpcpb.TxOutDetail\"w\n\nTxInDet" +
      "ail\022+\n\017prev_out_detail\030\001 \001(\0132\022.rpcpb.TxO" +
      "utDetail\022\022\n\nscript_sig\030\002 \001(\t\022\020\n\010sequence" +
      "\030\003 \001(\r\022\026\n\016prev_out_point\030\004 \001(\t\"\327\003\n\013TxOut" +
      "Detail\022\014\n\004addr\030\001 \001(\t\022\r\n\005value\030\002 \001(\004\022\026\n\016s" +
      "cript_pub_key\030\003 \001(\t\022\025\n\rscript_disasm\030\004 \001",
      "(\t\022*\n\004type\030\005 \001(\0162\034.rpcpb.TxOutDetail.TxO" +
      "utType\0221\n\020token_issue_info\030\006 \001(\0132\025.rpcpb" +
      ".TokenIssueInfoH\000\0227\n\023token_transfer_info" +
      "\030\007 \001(\0132\030.rpcpb.TokenTransferInfoH\000\0227\n\023sp" +
      "lit_contract_info\030\010 \001(\0132\030.rpcpb.SplitCon" +
      "tractInfoH\000\"\236\001\n\tTxOutType\022\013\n\007unknown\020\000\022\026" +
      "\n\022pay_to_pubkey_hash\020\001\022\033\n\027pay_to_pubkey_" +
      "hash_cltv\020\002\022\017\n\013token_issue\020\003\022\022\n\016token_tr" +
      "ansfer\020\004\022\022\n\016new_split_addr\020\005\022\026\n\022pay_to_s" +
      "cript_hash\020\006B\n\n\010appendix\"\316\001\n\013BlockDetail",
      "\022\017\n\007version\030\001 \001(\005\022\016\n\006height\030\002 \001(\r\022\022\n\ntim" +
      "e_stamp\030\003 \001(\003\022\014\n\004size\030\004 \001(\r\022\014\n\004hash\030\005 \001(" +
      "\t\022\027\n\017prev_block_hash\030\006 \001(\t\022\021\n\tcoin_base\030" +
      "\007 \001(\t\022\021\n\tconfirmed\030\010 \001(\010\022\021\n\tsignature\030\t " +
      "\001(\t\022\034\n\003txs\030\n \003(\0132\017.rpcpb.TxDetail\"4\n\016Tok" +
      "enIssueInfo\022\"\n\ttoken_tag\030\001 \001(\0132\017.rpcpb.T" +
      "okenTag\"3\n\021SplitContractInfo\022\r\n\005addrs\030\001 " +
      "\003(\t\022\017\n\007weights\030\002 \003(\004\"%\n\021TokenTransferInf" +
      "o\022\020\n\010token_id\030\001 \001(\t2\332\001\n\006WebApi\022?\n\014ViewTx" +
      "Detail\022\026.rpcpb.ViewTxDetailReq\032\027.rpcpb.V",
      "iewTxDetailResp\022H\n\017ViewBlockDetail\022\031.rpc" +
      "pb.ViewBlockDetailReq\032\032.rpcpb.ViewBlockD" +
      "etailResp\022E\n\025ListenAndReadNewBlock\022\026.rpc" +
      "pb.ListenBlocksReq\032\022.rpcpb.BlockDetail0\001" +
      "B\'\n\031one.contentbox.boxd.protoB\010WebProtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          one.contentbox.boxd.proto.TransactionProto.getDescriptor(),
        }, assigner);
    internal_static_rpcpb_ViewTxDetailReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpcpb_ViewTxDetailReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ViewTxDetailReq_descriptor,
        new java.lang.String[] { "Hash", "SpreadSplit", });
    internal_static_rpcpb_ViewTxDetailResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpcpb_ViewTxDetailResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ViewTxDetailResp_descriptor,
        new java.lang.String[] { "Code", "Message", "Version", "BlockTime", "BlockHeight", "Status", "Detail", });
    internal_static_rpcpb_ViewBlockDetailReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpcpb_ViewBlockDetailReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ViewBlockDetailReq_descriptor,
        new java.lang.String[] { "Hash", });
    internal_static_rpcpb_ViewBlockDetailResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpcpb_ViewBlockDetailResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ViewBlockDetailResp_descriptor,
        new java.lang.String[] { "Code", "Message", "Detail", });
    internal_static_rpcpb_ListenBlocksReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rpcpb_ListenBlocksReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_ListenBlocksReq_descriptor,
        new java.lang.String[] { });
    internal_static_rpcpb_TxDetail_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rpcpb_TxDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_TxDetail_descriptor,
        new java.lang.String[] { "Hash", "Vin", "Vout", });
    internal_static_rpcpb_TxInDetail_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rpcpb_TxInDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_TxInDetail_descriptor,
        new java.lang.String[] { "PrevOutDetail", "ScriptSig", "Sequence", "PrevOutPoint", });
    internal_static_rpcpb_TxOutDetail_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rpcpb_TxOutDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_TxOutDetail_descriptor,
        new java.lang.String[] { "Addr", "Value", "ScriptPubKey", "ScriptDisasm", "Type", "TokenIssueInfo", "TokenTransferInfo", "SplitContractInfo", "Appendix", });
    internal_static_rpcpb_BlockDetail_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rpcpb_BlockDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_BlockDetail_descriptor,
        new java.lang.String[] { "Version", "Height", "TimeStamp", "Size", "Hash", "PrevBlockHash", "CoinBase", "Confirmed", "Signature", "Txs", });
    internal_static_rpcpb_TokenIssueInfo_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rpcpb_TokenIssueInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_TokenIssueInfo_descriptor,
        new java.lang.String[] { "TokenTag", });
    internal_static_rpcpb_SplitContractInfo_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_rpcpb_SplitContractInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_SplitContractInfo_descriptor,
        new java.lang.String[] { "Addrs", "Weights", });
    internal_static_rpcpb_TokenTransferInfo_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_rpcpb_TokenTransferInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcpb_TokenTransferInfo_descriptor,
        new java.lang.String[] { "TokenId", });
    one.contentbox.boxd.proto.TransactionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
